export const BOOK_COPY = {
  en: {
    title: "Book a Vehicle",
    subtitle: "Browse available vehicles and submit your request",
    searchPlaceholder: "Search by make, model, or plate number...",
    allTypes: "All Types",
    allClasses: "All Classes",
    allAvailability: "All Availability",
    availableNow: "Available Now",
    inService: "Booked",
    requestBooking: "Request Vehicle",
    selectVehicle: "Select",
    selectedVehicle: "Selected",
    removeSelection: "Remove",
    viewDetails: "Details",
    seats: "{count} seats",
    selectedCountOne: "1 vehicle selected",
    selectedCountMany: "{count} vehicles selected",
    readyToDispatch: "Ready to dispatch",
    clearSelection: "Clear",
    requestCart: "Continue",
    signIn: "Sign In",
    statusAvailable: "Available Now",
    statusBusy: "Booked — Available:",
    loadingCatalog: "Loading available vehicles...",
    loadingMore: "Loading more vehicles...",
    noVehiclesTitle: "No vehicles found",
    noVehiclesSearch: "No vehicles match “{query}”. Try a different make, model, or plate number.",
    noVehiclesFiltered: "No vehicles match your current filters. Adjust type, class, or availability and try again.",
    noVehiclesEmpty: "There are no vehicles available right now. Please check back later.",
    clearFilters: "Clear",
    showingCount: "{count} vehicles",
    showingCountOne: "1 vehicle",
    showingProgress: "Showing {visible} of {total} vehicles",
    allLoaded: "All {total} vehicles loaded",
    loadMore: "Load more vehicles (+{count})",
  },
  am: {
    title: "ተሽከርካሪ ይዘዙ",
    subtitle: "ያሉትን ተሽከርካሪዎች ይመልከቱ እና የጉዞ ጥያቄዎን ያስገቡ",
    searchPlaceholder: "በብራንድ፣ በሞዴል ወይም በሰሌዳ ቁጥር ይፈልጉ...",
    allTypes: "ሁሉም ዓይነቶች",
    allClasses: "ሁሉም ክፍሎች",
    allAvailability: "ሁሉም ዝግጁነት",
    availableNow: "አሁን የሚገኙ",
    inService: "ተይዘዋል",
    requestBooking: "ተሽከርካሪ ይጠይቁ",
    selectVehicle: "ይምረጡ",
    selectedVehicle: "ተመርጧል",
    removeSelection: "አስወግድ",
    viewDetails: "ዝርዝር",
    seats: "{count} መቀመጫ",
    selectedCountOne: "1 ተሽከርካሪ ተመርጧል",
    selectedCountMany: "{count} ተሽከርካሪዎች ተመርጠዋል",
    readyToDispatch: "ለመላኪያ ዝግጁ",
    clearSelection: "አጽዳ",
    requestCart: "ቀጥል",
    signIn: "ግባ",
    statusAvailable: "አሁን ይገኛል",
    statusBusy: "ተይዟል — የሚገኝበት ጊዜ፡",
    loadingCatalog: "የተሽከርካሪ ካታሎግ በመጫን ላይ...",
    loadingMore: "ተጨማሪ ተሽከርካሪዎችን በመጫን ላይ...",
    noVehiclesTitle: "ምንም ተሽከርካሪ አልተገኘም",
    noVehiclesSearch: "“{query}” ጋር የሚዛመድ ተሽከርካሪ የለም። ሌላ ብራንድ፣ ሞዴል ወይም ሰሌዳ ቁጥር ይሞክሩ።",
    noVehiclesFiltered: "ከአሁኑ ማጣሪያዎች ጋር የሚዛመድ ተሽከርካሪ የለም። ዓይነት፣ ክፍል ወይም ዝግጁነትን ቀይረው እንደገና ይሞክሩ።",
    noVehiclesEmpty: "በአሁኑ ሰዓት በካታሎጉ ውስጥ ምንም ተሽከርካሪ የለም። እባክዎ ቆይተው እንደገና ይመልከቱ።",
    clearFilters: "አጽዳ",
    showingCount: "{count} ተሽከርካሪዎች",
    showingCountOne: "1 ተሽከርካሪ",
    showingProgress: "ከ{total} ውስጥ {visible} ተሽከርካሪዎች በመታየት ላይ",
    allLoaded: "ሁሉንም {total} ተሽከርካሪዎች አይተዋል",
    loadMore: "ተጨማሪ ተሽከርካሪዎችን አሳይ (+{count})",
  },
} as const;

export type BookCopy = Record<keyof typeof BOOK_COPY["en"], string>;

export const staggerContainer = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: { staggerChildren: 0.05 },
  },
};

export const cardVariant = {
  hidden: { opacity: 0, y: 25 },
  show: { opacity: 1, y: 0, transition: { duration: 0.5, ease: "easeOut" as const } },
};
