import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Award,
  Bell,
  Circle,
  ClipboardCheck,
  CalendarClock,
  ClipboardList,
  IdCard,
  Key,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Mail,
  Map,
  MapPin,
  Menu,
  MessageSquare,
  Palette,
  Receipt,
  ReceiptText,
  Route,
  ScrollText,
  Send,
  Settings,
  Clock3,
  CreditCard,
  Shield,
  ShieldCheck,
  Truck,
  Users,
  UserRound,
  Wrench,
  Coins,
  FileText,
  Fuel,
} from "lucide-react";

const MENU_ICON_MAP: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  "user-round": UserRound,
  dashboard: LayoutDashboard,
  users: Users,
  "id-card": IdCard,
  drivers: IdCard,
  "drivers-directory": IdCard,
  "calendar-clock": CalendarClock,
  "drivers-shifts": CalendarClock,
  "drivers-attendance": Clock3,
  activity: Activity,
  "drivers-performance": Activity,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  shield: Shield,
  "shield-check": ShieldCheck,
  roles: Shield,
  key: Key,
  permissions: Key,
  menu: Menu,
  menus: Menu,
  route: Route,
  endpoints: Route,
  "scroll-text": ScrollText,
  "audit-logs": ScrollText,
  settings: Settings,
  "system-settings": Settings,
  clock: Clock3,
  "deadline-settings": Clock3,
  palette: Palette,
  "branding-settings": Palette,
  "credit-card": CreditCard,
  "payment-gateway-settings": CreditCard,
  "access-control": ShieldCheck,
  bell: Bell,
  notifications: Bell,
  send: Send,
  "notification-send": Send,
  "messages-square": MessageSquare,
  "notification-templates": MessageSquare,
  mail: Mail,
  "message-square": MessageSquare,
  truck: Truck,
  fleet: Truck,
  "fleet-vehicles": Truck,
  "fleet-setup": Layers,
  layers: Layers,
  "vehicle-types": Layers,
  award: Award,
  "vehicle-classes": Award,
  wrench: Wrench,
  "maintenance-work-types": Wrench,
  "fleet-maintenance": Wrench,
  fuel: Fuel,
  "fleet-fuel": Fuel,
  map: Map,
  "map-pin": MapPin,
  "location-management": Map,
  "location-regions": Map,
  "location-sites": MapPin,
  receipt: Receipt,
  billing: Receipt,
  coins: Coins,
  "fare-plans": Coins,
  "booking-policies": ClipboardList,
  "file-text": FileText,
  contracts: FileText,
  "receipt-text": ReceiptText,
  invoices: ReceiptText,
  complaints: MessageSquare,
  "customer-complaints": MessageSquare,
};

export function getMenuIcon(icon?: string | null): LucideIcon {
  if (!icon) return Circle;
  const normalized = icon.trim().toLowerCase();
  return MENU_ICON_MAP[normalized] ?? Circle;
}
